name: dynamic_id_image_cache
description: A new Flutter package project.
version: 0.0.1
author: Guilherme Lima Gabanelli
homepage: https://github.com/Gabanelli

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
