name: dynamic_url_image_cache
description: A image widget that caches the image with an ID, useful for images with dynamic urls, like S3 images.
version: 0.0.2
homepage: https://github.com/Gabanelli
repository: https://github.com/Gabanelli/dynamic_url_image_cache

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  path_provider: ^1.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
